CREATE TABLE <your_curated_glue_db>.cds_po_item (
  purchaseorder string COMMENT 'Purchase_Order',
  purchaseorderitem string COMMENT 'Purchase_Order_Item',
  purchaseordertype string COMMENT 'PO_Type',
  purchasinggroup string COMMENT 'Purch_Group',
  purchasingorganization string COMMENT 'Purchasing_Org',
  purchasingdocumentorigin string COMMENT 'Status',
  supplier string COMMENT 'Supplier',
  supplyingsupplier string COMMENT 'Goods_Supplier',
  supplyingplant string COMMENT 'Supplying_Plant',
  documentcurrency string COMMENT 'Currency',
  exchangerate double COMMENT '',
  invoicingparty string COMMENT 'Invoicing_Party',
  purchaseorderdate string COMMENT 'PO_Date',
  validitystartdate string COMMENT 'Validity_Start',
  validityenddate string COMMENT 'Validity_End',
  purchasingdocumentdeletioncode string COMMENT 'Del_Indicator',
  materialgroup string COMMENT 'Material_Group',
  material string COMMENT 'Material',
  manufacturermaterial string COMMENT 'Material',
  purchaseordercategory string COMMENT 'Doc_Category',
  purchasingorderreason string COMMENT 'Reason_for_Ord',
  purchaseorderitemtext string COMMENT 'Short_Text',
  purchaseorderitemcategory string COMMENT 'Item_Category',
  companycode string COMMENT 'Company_Code',
  plant string COMMENT 'Plant',
  storagelocation string COMMENT 'Storage_Location',
  purchasecontract string COMMENT 'Agreement',
  purchasecontractitem string COMMENT 'Agreement_Item',
  baseunit string COMMENT 'Base_Unit',
  orderquantity double COMMENT '',
  purchaseorderquantityunit string COMMENT 'Order_Unit',
  netpriceamount double COMMENT '',
  netamount double COMMENT '',
  localcurrency string COMMENT 'Currency',
  netpricequantity double COMMENT 'Price_Unit',
  orderpriceunit string COMMENT 'Order_Price_Un',
  requisitionername string COMMENT 'Requisitioner',
  retailpromotion string COMMENT 'Promotion',
  iscompletelydelivered string COMMENT 'Deliv_Compl',
  isfinallyinvoiced string COMMENT 'Final_Invoice',
  invoiceisexpected string COMMENT 'Invoice_Receipt',
  orderitemqtytobaseqtydnmntr double COMMENT 'Denominator',
  orderitemqtytobaseqtynmrtr double COMMENT 'Equal_To',
  invoiceisgoodsreceiptbased string COMMENT 'GRBased_IV',
  goodsreceiptisexpected string COMMENT 'Goods_Receipt',
  evaldrcptsettlmtisallowed string COMMENT 'ERS',
  odq_changemode string COMMENT 'String',
  odq_entitycntr double COMMENT 'Number_of_Data_Units_Data_Records_for_Example',
  loadts timestamp COMMENT 'Load Timestamp',
  counter int COMMENT 'Record Counter')
LOCATION 's3://<your_curated_s3_bucket>/cds_po_item'
TBLPROPERTIES (
  'table_type'='iceberg'
);