CREATE TABLE afsaplakecurated.cds_sch_agreem_header (
  schedulingagreement string COMMENT 'Purchasing_Doc',
  companycode string COMMENT 'Company_Code',
  purchasingdocumentcategory string COMMENT 'Doc_Category',
  purchasingdocumenttype string COMMENT 'Document_Type',
  createdbyuser string COMMENT 'Created_By',
  creationdate string COMMENT 'Created_On',
  language string COMMENT 'Language',
  purchasingorganization string COMMENT 'Purchasing_Org',
  purchasinggroup string COMMENT 'Purch_Group',
  documentcurrency string COMMENT 'Currency',
  incotermsclassification string COMMENT 'Incoterms',
  incotermstransferlocation string COMMENT 'Incoterms_2',
  paymentterms string COMMENT 'Payment_Terms',
  cashdiscount1days double COMMENT 'Days_1',
  cashdiscount2days double COMMENT 'Days_2',
  cashdiscount1percent double COMMENT '',
  cashdiscount2percent double COMMENT '',
  netpaymentdays double COMMENT 'Days_Net',
  targetamount double COMMENT '',
  exchangerate double COMMENT '',
  exchangerateisfixed string COMMENT 'Fixed_ExchRate',
  incotermslocation1 string COMMENT 'Inco_Location1',
  incotermslocation2 string COMMENT 'Inco_Location2',
  incotermsversion string COMMENT 'Inco_Version',
  purchasingdocumentorderdate string COMMENT 'Document_Date',
  scheduleagreementhasreleasedoc string COMMENT 'Release_docu',
  supplier string COMMENT 'Supplier',
  supplieraddressid string COMMENT 'Address_Number',
  validitystartdate string COMMENT 'Validity_Start',
  validityenddate string COMMENT 'Validity_End',
  purchasingdocumentorigin string COMMENT 'Status',
  purchasingdocumentdeletioncode string COMMENT 'Del_Indicator',
  quotationsubmissiondate string COMMENT 'Quotation_Date',
  supplierquotationexternalid string COMMENT 'Quotation',
  supplierrespsalespersonname string COMMENT 'Salesperson',
  supplierphonenumber string COMMENT 'Supplier_Phone',
  invoicingparty string COMMENT 'Invoicing_Party',
  supplyingsupplier string COMMENT 'Goods_Supplier',
  companyvatregistration string COMMENT 'VAT_Reg_No',
  vatregistrationcountry string COMMENT 'CtryRgnSlsTxNo',
  lastchangedatetime double COMMENT 'Last_Changed',
  odq_changemode string COMMENT 'String',
  odq_entitycntr double COMMENT 'Number_of_Data_Units_Data_Records_for_Example',
  loadts timestamp COMMENT 'Load Timestamp',
  counter int COMMENT 'Record Counter')
LOCATION 's3://afsapcurated/cds_sch_agreem_header'
TBLPROPERTIES (
  'table_type'='iceberg'
);