CREATE TABLE <your_curated_glue_db>.cds_po_header (
  purchaseorder string COMMENT 'Purchase_Order',
  purchaseordertype string COMMENT 'PO_Type',
  purchaseordersubtype string COMMENT 'Control',
  purchasingdocumentorigin string COMMENT 'Status',
  createdbyuser string COMMENT 'Created_By',
  creationdate string COMMENT 'Created_On',
  purchaseorderdate string COMMENT 'PO_Date',
  language string COMMENT 'Language',
  correspncexternalreference string COMMENT 'Your_Reference',
  correspncinternalreference string COMMENT 'Our_Reference',
  purchasingdocumentdeletioncode string COMMENT 'Del_Indicator',
  releaseisnotcompleted string COMMENT 'Subjto_Release',
  purchasingcompletenessstatus string COMMENT 'Incomplete',
  purchasingprocessingstatus string COMMENT 'Proc_State',
  purgreleasesequencestatus string COMMENT 'Release_State',
  releasecode string COMMENT 'Release_ind',
  companycode string COMMENT 'Company_Code',
  purchasingorganization string COMMENT 'Purchasing_Org',
  purchasinggroup string COMMENT 'Purch_Group',
  supplier string COMMENT 'Supplier',
  manualsupplieraddressid string COMMENT 'Address_Number',
  supplierrespsalespersonname string COMMENT 'Salesperson',
  supplierphonenumber string COMMENT 'Telephone',
  supplyingsupplier string COMMENT 'Goods_Supplier',
  supplyingplant string COMMENT 'Supplying_Plant',
  invoicingparty string COMMENT 'Invoicing_Party',
  customer string COMMENT 'Customer',
  supplierquotationexternalid string COMMENT 'Quotation',
  paymentterms string COMMENT 'Payment_Terms',
  cashdiscount1days double COMMENT 'Days_1',
  cashdiscount2days double COMMENT 'Days_2',
  netpaymentdays double COMMENT 'Days_Net',
  cashdiscount1percent double COMMENT '',
  cashdiscount2percent double COMMENT '',
  downpaymenttype string COMMENT 'Down_Payment',
  downpaymentpercentageoftotamt double COMMENT '',
  downpaymentamount double COMMENT '',
  downpaymentduedate string COMMENT 'Due_Date_for_DP',
  incotermsclassification string COMMENT 'Incoterms',
  incotermstransferlocation string COMMENT 'Incoterms_2',
  incotermsversion string COMMENT 'Inco_Version',
  incotermslocation1 string COMMENT 'Inco_Location1',
  incotermslocation2 string COMMENT 'Inco_Location2',
  isintrastatreportingrelevant string COMMENT 'Intrastat_rel',
  isintrastatreportingexcluded string COMMENT 'exclude_Intra',
  pricingdocument string COMMENT 'Doc_Condition',
  pricingprocedure string COMMENT 'Procedure',
  documentcurrency string COMMENT 'Currency',
  validitystartdate string COMMENT 'Validity_Start',
  validityenddate string COMMENT 'Validity_End',
  exchangerate double COMMENT '',
  exchangerateisfixed string COMMENT 'Fixed_ExchRate',
  lastchangedatetime double COMMENT 'Last_Changed',
  taxreturncountry string COMMENT 'Reporting_CR',
  vatregistrationcountry string COMMENT 'CtryRgnSlsTxNo',
  purgreasonfordoccancellation string COMMENT 'Reas_for_Canc',
  purgreleasetimetotalamount double COMMENT '',
  odq_changemode string COMMENT 'String',
  odq_entitycntr double COMMENT 'Number_of_Data_Units_Data_Records_for_Example',
  loadts timestamp COMMENT 'Load Timestamp',
  counter int COMMENT 'Record Counter')
LOCATION 's3://<your_curated_s3_bucket>/cds_po_header'
TBLPROPERTIES (
  'table_type'='iceberg'
);