CREATE TABLE afsaplakecurated.cds_po_confirmation (
  purchaseorder string COMMENT 'Purchase_Order',
  purchaseorderitem string COMMENT 'Purchase_Order_Item',
  sequentialnmbrofsuplrconf string COMMENT 'Sequential_No',
  supplierconfirmationcategory string COMMENT 'Confirm_Cat',
  deliverydate string COMMENT 'Delivery_Date',
  delivdatecategory string COMMENT 'Delivery_Date',
  deliverytime string COMMENT 'Time',
  creationdate string COMMENT 'Created_on',
  creationtime string COMMENT 'Creation_Time',
  confirmedquantity double COMMENT '',
  mrprelevantquantity double COMMENT '',
  suplrconfcreationcategory string COMMENT 'Creation_ind',
  isdeleted string COMMENT 'Deletion_Ind',
  confisrelevanttomrp string COMMENT 'MRPRelevant',
  supplierconfirmationextnumber string COMMENT 'Reference',
  deliverydocument string COMMENT 'Delivery',
  deliverydocumentitem string COMMENT 'Item',
  manufacturerpartprofile string COMMENT 'Mfr_part_profile',
  manufacturermaterial string COMMENT 'MPN_material',
  numberofreminders double COMMENT 'No_RemExp',
  batch string COMMENT 'Batch',
  deliveryisinplant string COMMENT 'In_Plant',
  handoverdate string COMMENT 'Handover_Date',
  handovertime string COMMENT 'Handover_Time',
  performanceperiodstartdate string COMMENT 'Start_Date',
  performanceperiodenddate string COMMENT 'End_Date',
  serviceperformer string COMMENT 'Service_Performer',
  orderquantityunit string COMMENT 'Order_Unit',
  supplierconfirmation string COMMENT 'Confirmation',
  supplierconfirmationitem string COMMENT 'Confirmation_Item',
  purchaseordertype string COMMENT 'PO_Type',
  purchasingorganization string COMMENT 'Purchasing_Org',
  purchasinggroup string COMMENT 'Purch_Group',
  plant string COMMENT 'Plant',
  odq_changemode string COMMENT 'String',
  odq_entitycntr double COMMENT 'Number_of_Data_Units_Data_Records_for_Example',
  loadts timestamp COMMENT 'Load Timestamp',
  counter int COMMENT 'Record Counter')
LOCATION 's3://afsapcurated/cds_po_confirmation'
TBLPROPERTIES (
  'table_type'='iceberg'
);