CREATE TABLE afsaplakecurated.cds_po_acc_assignment (
  purchaseorder string COMMENT 'Purchasing_Doc',
  purchaseorderitem string COMMENT 'Item',
  accountassignmentnumber string COMMENT 'Account_Assgmt_No',
  costcenter string COMMENT 'Cost_Center',
  masterfixedasset string COMMENT 'Asset',
  projectnetwork string COMMENT 'Network',
  quantity double COMMENT '',
  purchaseorderquantityunit string COMMENT 'Order_Unit',
  multipleacctassgmtdistrpercent double COMMENT '',
  purgdocnetamount double COMMENT '',
  documentcurrency string COMMENT 'Currency',
  isdeleted string COMMENT 'Deletion_Ind',
  glaccount string COMMENT 'GL_Account',
  businessarea string COMMENT 'Business_Area',
  salesorder string COMMENT 'SD_Document',
  salesorderitem string COMMENT 'Item',
  salesorderscheduleline string COMMENT 'Schedule_Line',
  fixedasset string COMMENT 'Subnumber',
  orderid string COMMENT 'Order',
  unloadingpointname string COMMENT 'Unloading_Point',
  controllingarea string COMMENT 'CO_Area',
  costobject string COMMENT 'Cost_Object',
  profitabilitysegment string COMMENT 'Profitability_Segment_Deprecated',
  profitabilitysegment_2 string COMMENT 'Profitability_Segment',
  profitcenter string COMMENT 'Profit_Center',
  wbselementinternalid string COMMENT 'WBS_Internal_ID',
  projectnetworkinternalid string COMMENT 'Plan_nofoper',
  commitmentitem string COMMENT 'String',
  fundscenter string COMMENT 'Funds_Center',
  fund string COMMENT 'Fund',
  functionalarea string COMMENT 'Functional_Area',
  goodsrecipientname string COMMENT 'Recipient',
  isfinallyinvoiced string COMMENT 'Final_Invoice',
  realestateobject string COMMENT 'Real_Estate_Key',
  networkactivityinternalid string COMMENT 'Counter',
  partneraccountnumber string COMMENT 'Partner',
  jointventurerecoverycode string COMMENT 'Recovery_Ind',
  settlementreferencedate string COMMENT 'Reference_date',
  orderinternalid string COMMENT 'Plan_nofoper',
  orderintbillofoperationsitem string COMMENT 'Counter',
  taxcode string COMMENT 'Tax_Code',
  taxjurisdiction string COMMENT 'Tax_Jur',
  nondeductibleinputtaxamount double COMMENT '',
  costctractivitytype string COMMENT 'Activity_Type',
  businessprocess string COMMENT 'Business_Process',
  grantid string COMMENT 'Grant',
  budgetperiod string COMMENT 'Budget_Period',
  earmarkedfundsdocument string COMMENT 'Earmarked_Funds',
  earmarkedfundsdocumentitem string COMMENT 'Document_Item',
  servicedocumenttype string COMMENT 'Service_Doc_Type',
  servicedocument string COMMENT 'Service_Document',
  servicedocumentitem string COMMENT 'Service_Doc_Item',
  purchaseordertype string COMMENT 'PO_Type',
  purchasingorganization string COMMENT 'Purchasing_Org',
  purchasinggroup string COMMENT 'Purch_Group',
  plant string COMMENT 'Plant',
  accountassignmentcategory string COMMENT 'Acct_Assgmt_Cat',
  odq_changemode string COMMENT 'String',
  odq_entitycntr double COMMENT 'Number_of_Data_Units_Data_Records_for_Example',
  loadts timestamp COMMENT 'Load Timestamp',
  counter int COMMENT 'Record Counter')
LOCATION 's3://afsapcurated/cds_po_acc_assignment'
TBLPROPERTIES (
  'table_type'='iceberg'
);