CREATE TABLE <your_curated_glue_db>.cds_po_schedule_line (
  purchaseorder string COMMENT 'Purchasing_Doc',
  purchaseorderitem string COMMENT 'Item',
  purchaseorderscheduleline string COMMENT 'Schedule_Line',
  schedulelinedeliverydate string COMMENT 'Delivery_Date',
  schedulelinedeliverytime string COMMENT 'Time',
  purchaserequisition string COMMENT 'Purchase_Req',
  purchaserequisitionitem string COMMENT 'Requisn_item',
  batch string COMMENT 'Batch',
  purchasingschdlnnrofreminders double COMMENT 'No_RemExp',
  requisitionername string COMMENT 'Requisitioner',
  retailpromotion string COMMENT 'Promotion',
  articlecategory string COMMENT 'Matl_Category',
  purchasingorderreason string COMMENT 'Reason_for_Ord',
  iscompletelydelivered string COMMENT 'Deliv_Compl',
  manufacturermaterial string COMMENT 'Material',
  isfinallyinvoiced string COMMENT 'Final_Invoice',
  purchasecontract string COMMENT 'Agreement',
  purchasecontractitem string COMMENT 'Agreement_Item',
  storagelocation string COMMENT 'Storage_Location',
  baseunit string COMMENT 'Base_Unit',
  materialgroup string COMMENT 'Material_Group',
  material string COMMENT 'Material',
  purchaseorderquantityunit string COMMENT 'Order_Unit',
  purchaseorderitemcategory string COMMENT 'Item_Category',
  issuingstoragelocation string COMMENT 'Iss_Stor_Loc',
  purchaseorderitemtext string COMMENT 'Short_Text',
  purchasingparentitem string COMMENT 'HLev_Item',
  orderitemqtytobaseqtydnmntr double COMMENT 'Denominator',
  orderitemqtytobaseqtynmrtr double COMMENT 'Equal_To',
  invoiceisgoodsreceiptbased string COMMENT 'GRBased_IV',
  goodsreceiptisexpected string COMMENT 'Goods_Receipt',
  plant string COMMENT 'Plant',
  evaldrcptsettlmtisallowed string COMMENT 'ERS',
  purchaseorderdate string COMMENT 'PO_Date',
  purchaseordertype string COMMENT 'PO_Type',
  purchasinggroup string COMMENT 'Purch_Group',
  purchasingorganization string COMMENT 'Purchasing_Org',
  validitystartdate string COMMENT 'Validity_Start',
  validityenddate string COMMENT 'Validity_End',
  supplier string COMMENT 'Supplier',
  invoicingparty string COMMENT 'Invoicing_Party',
  supplyingsupplier string COMMENT 'Goods_Supplier',
  supplyingplant string COMMENT 'Supplying_Plant',
  purchasingdocumentorigin string COMMENT 'Status',
  documentcurrency string COMMENT 'Currency',
  exchangerate double COMMENT '',
  delivdatecategory string COMMENT 'Delivery_Date',
  schedulelineorderquantity double COMMENT '',
  prevdelivqtyofscheduleline double COMMENT '',
  roughgoodsreceiptqty double COMMENT '',
  schedulelineissuedquantity double COMMENT '',
  sourceofcreation string COMMENT 'Creation_ind',
  reservation string COMMENT 'Reservation',
  schedulelineisfixed string COMMENT 'Fixing_Ind',
  stocktransferdeliveredquantity double COMMENT '',
  schedulelinecommittedquantity double COMMENT '',
  productavailabilitydate string COMMENT 'MatAvailDate',
  productavailabilitytime string COMMENT 'Matl_Staging_Tme',
  loadingdate string COMMENT 'Loading_Date',
  loadingtime string COMMENT 'Loading_Time',
  transportationplanningdate string COMMENT 'TranspPlngDate',
  transportationplanningtime string COMMENT 'Tr_Plan_Time',
  goodsissuedate string COMMENT 'Goods_Issue',
  goodsissuetime string COMMENT 'GI_Time',
  stolatestpossiblegrdate string COMMENT 'GR_End_Date',
  stolatestpossiblegrtime string COMMENT 'GR_End_Time',
  openpurchaseordernetamount double COMMENT '',
  odq_changemode string COMMENT 'String',
  odq_entitycntr double COMMENT 'Number_of_Data_Units_Data_Records_for_Example',
  loadts timestamp COMMENT 'Load Timestamp',
  counter int COMMENT 'Record Counter')
LOCATION 's3://<your_curated_s3_bucket>/cds_po_schedule_line'
TBLPROPERTIES (
  'table_type'='iceberg'
);



