CREATE TABLE afsaplakecurated.cds_pur_contract_header (
  purchasecontract string COMMENT 'Purchase_Contract',
  purchasecontracttype string COMMENT 'Document_Type',
  purchasinggroup string COMMENT 'Purch_Group',
  purchasingorganization string COMMENT 'Purchasing_Org',
  validitystartdate string COMMENT 'Validity_Start',
  validityenddate string COMMENT 'Validity_End',
  supplier string COMMENT 'Supplier',
  invoicingparty string COMMENT 'Invoicing_Party',
  supplyingsupplier string COMMENT 'Goods_Supplier',
  creationdate string COMMENT 'Created_On',
  documentcurrency string COMMENT 'Currency',
  exchangerate double COMMENT '',
  purchasingdocumentcategory string COMMENT 'Doc_Category',
  companycode string COMMENT 'Company_Code',
  incotermsclassification string COMMENT 'Incoterms',
  incotermstransferlocation string COMMENT 'Incoterms_2',
  paymentterms string COMMENT 'Payment_Terms',
  cashdiscount1days double COMMENT 'Days_1',
  cashdiscount2days double COMMENT 'Days_2',
  netpaymentdays double COMMENT 'Days_Net',
  cashdiscount1percent double COMMENT '',
  cashdiscount2percent double COMMENT '',
  purchasecontracttargetamount double COMMENT '',
  releasecode string COMMENT 'Release_ind',
  createdbyuser string COMMENT 'Created_By',
  purchasingdocumentdeletioncode string COMMENT 'Del_Indicator',
  exchangerateisfixed string COMMENT 'Fixed_ExchRate',
  quotationsubmissiondate string COMMENT 'Quotation_Date',
  supplierquotation string COMMENT 'Quotation',
  correspncexternalreference string COMMENT 'Your_Reference',
  correspncinternalreference string COMMENT 'Our_Reference',
  supplierrespsalespersonname string COMMENT 'Salesperson',
  supplierphonenumber string COMMENT 'Supplier_Phone',
  incotermsversion string COMMENT 'Inco_Version',
  incotermslocation1 string COMMENT 'Inco_Location1',
  incotermslocation2 string COMMENT 'Inco_Location2',
  releaseisnotcompleted string COMMENT 'Subjto_Release',
  supplieraddressid string COMMENT 'Address_Number',
  odq_changemode string COMMENT 'String',
  odq_entitycntr double COMMENT 'Number_of_Data_Units_Data_Records_for_Example',
  loadts timestamp COMMENT 'Load Timestamp',
  counter int COMMENT 'Record Counter')
LOCATION 's3://afsapcurated/cds_pur_contract_header'
TBLPROPERTIES (
  'table_type'='iceberg'
);