CREATE TABLE <your_curated_glue_db>.cds_supplier_invoice (
  supplierinvoice string COMMENT 'Document_Number',
  fiscalyear string COMMENT 'Fiscal_Year',
  supplierinvoiceitem string COMMENT 'Item',
  qtyinpurchaseorderpriceunit double COMMENT '',
  purchaseorderpriceunit string COMMENT 'PO_Price_Unit',
  purchaseorderquantityunit string COMMENT 'Order_Unit',
  purchaseorder string COMMENT 'Purchasing_Doc',
  purchaseorderitem string COMMENT 'Item',
  prmthbreferencedocument string COMMENT 'Reference_Doc',
  prmthbreferencedocumentfsclyr string COMMENT 'Year_curperiod',
  prmthbreferencedocumentitem string COMMENT 'Ref_Doc_Item',
  purchaseorderitemmaterial string COMMENT 'Material',
  quantityinpurchaseorderunit double COMMENT '',
  suplrinvcitmhasqualityvariance string COMMENT 'Block_Quality',
  suplrinvcitemhasordprcqtyvarc string COMMENT 'BlockReas_OPQ',
  suplrinvcitemhasqtyvariance string COMMENT 'BlockReasQty',
  suplrinvcitemhaspricevariance string COMMENT 'BlockReasPrc',
  suplrinvcitemhasothervariance string COMMENT 'ManBlockReasn',
  suplrinvcitemhasamountoutsdtol string COMMENT 'Blkg_Reas_Amount',
  suplrinvcitemhasdatevariance string COMMENT 'Bl_Reason_Date',
  issubsequentdebitcredit string COMMENT 'Subseq_DrCr',
  plant string COMMENT 'Plant',
  documentcurrency string COMMENT 'Currency',
  supplierinvoiceitemamount double COMMENT '',
  suplrinvcautomreducedamount double COMMENT '',
  unplanneddeliverycost double COMMENT '',
  documentheadertext string COMMENT 'DocHeader_Text',
  documentdate string COMMENT 'Invoice_Date',
  postingdate string COMMENT 'Posting_Date',
  companycode string COMMENT 'Company_Code',
  supplierinvoiceorigin string COMMENT 'IV_category',
  invoicingparty string COMMENT 'Invoicing_Party',
  unplanneddeliverycosttaxcode string COMMENT 'Tax_Code',
  reversedocument string COMMENT 'Reversed_by',
  reversedocumentfiscalyear string COMMENT 'Year',
  supplierinvoiceidbyinvcgparty string COMMENT 'Reference',
  isinvoice string COMMENT 'Invoice',
  supplierinvoicestatus string COMMENT 'Inv_status',
  odq_changemode string COMMENT 'String',
  odq_entitycntr double COMMENT 'Number_of_Data_Units_Data_Records_for_Example',
  loadts timestamp COMMENT 'Load Timestamp',
  counter int COMMENT 'Record Counter')
LOCATION 's3://<your_curated_s3_bucket>/cds_supplier_invoice'
TBLPROPERTIES (
  'table_type'='iceberg'
);